In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np 
arr = np.array([1000, 2000, 3000])

print(arr + 500)
print(arr * 2)
print(arr // 100)

[1500 2500 3500]
[2000 4000 6000]
[10 20 30]


In [3]:
arr = np.array([1000, 2000, 3000, 4000])

print(arr.mean())   # average
print(arr.sum())    # total
print(arr.max())    # highest
print(arr.min())    # lowest
print(arr.std())    # standard deviation

2500.0
10000
4000
1000
1118.033988749895


**Basic Statictics**


. Risk analysis
. Transaction analysis


In [4]:
arr = np.array([1000, 20000, 5000, 70000])
high = arr[arr > 10000]
print(high)

[20000 70000]


In [5]:
trn_amt = np.array([1000, 2000, 3000, 4000])
print(trn_amt * 1.05)

[1050. 2100. 3150. 4200.]


In [6]:
print(trn_amt.sum())

10000


In [7]:
arr = np.array([500, 15000, 3000, 70000, 200])
subtract = arr - 500
print(subtract)

[    0 14500  2500 69500  -300]


In [8]:
returns = np.array([0.02, -0.01, 0.015, -0.03, 0.01])
cumulative = np.cumprod(1 + returns) - 1
print(cumulative)

[ 0.02        0.0098      0.024947   -0.00580141  0.00414058]


cummulative return is the total percentage change in an investment over a period of time which represent total profit or loss without annualizing the rate.

to cal this we need to convert percentage into growth factors and multiply the growth factors, which is why i added one. now, substract one to get its original value

In [9]:
transactions = np.array([1000, 2000, 3000, 4000])

fees = transactions * 0.10
print(fees)

[100. 200. 300. 400.]


In [10]:
transactions = np.array([
    [1000, 2000, 3000],
    [4000, 5000, 6000],
    [7000, 8000, 9000]
])

row_totals = transactions.sum(axis=1)
print(row_totals)

[ 6000 15000 24000]


In [11]:
amount = np.array([1000, 5000, 20000, 75000, 120000])
risk_arr = np.select(
    [amount <= 10000,
    amount <= 50000,
    amount > 50000],
    [0, 1, 2]
)
print(risk_arr)

[0 0 1 2 2]


In [12]:
risk_arr = np.where(
    amount <= 10000, 0,
    np.where(amount <= 50000, 1, 2)
)
print(risk_arr)

[0 0 1 2 2]


In [13]:
import numpy as np

transactions = np.array([1000, 2000, 3000])
fee_rate = 0.05

fees = transactions * fee_rate
print(fees)

[ 50. 100. 150.]


In [14]:
transactions = np.array([
    [1000, 2000, 3000],
    [4000, 5000, 6000]
])

fee_rates = np.array([0.05, 0.1, 0.2])

fees = transactions * fee_rates
print(fees)

[[  50.  200.  600.]
 [ 200.  500. 1200.]]


Broadcasting with 2D

In [15]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


Used in 

. Portfolio allocation
. Linear regression
. Risk modeling


In [16]:
np.random.seed(42)

returns = np.random.normal(
    loc=0.001,     # mean return
    scale=0.02,    # volatility
    size=5
)

print(returns)

[ 0.01093428 -0.00176529  0.01395377  0.0314606  -0.00368307]


In [17]:
np.random.seed(42)

initial_investment = 10000
days = 252  # trading days
simulations = 1000

returns = np.random.normal(0.001, 0.02, (days, simulations))

portfolio = initial_investment * np.cumprod(1 + returns, axis=0)

final_values = portfolio[-1]

print(final_values.mean())
print(final_values.min())
print(final_values.max())

12882.156529490941
4584.858691704849
30709.839555969083


In [18]:
asset1 = np.random.normal(0.001, 0.02, 1000)
asset2 = np.random.normal(0.001, 0.03, 1000)

correlation = np.corrcoef(asset1, asset2)
print(correlation)

[[1.        0.0323687]
 [0.0323687 1.       ]]


In [19]:
np.random.seed(42)
returns = np.random.normal(
    loc = 0.002,
    scale = 0.01,
    size = 10
)
print(returns)

[ 0.00696714  0.00061736  0.00847689  0.0172303  -0.00034153 -0.00034137
  0.01779213  0.00967435 -0.00269474  0.0074256 ]


In [20]:
cumulative_returns = np.cumprod(1 + returns) -1
print(cumulative_returns)

[0.00696714 0.0075888  0.01613001 0.03363824 0.03328522 0.03293248
 0.05131055 0.06148129 0.05862087 0.06648177]


In [21]:
np.random.seed(42)

days = 100
portfolios = 500

returns = np.random.normal(0.002, 0.01, (days, portfolios))
print(returns)

[[ 6.96714153e-03  6.17356988e-04  8.47688538e-03 ...  9.66132192e-05
  -6.75618253e-03 -1.18279973e-02]
 [ 1.12617755e-02  2.10941664e-02 -1.19856757e-02 ...  8.40842861e-03
  -3.71178990e-03  7.72582781e-03]
 [ 1.59935544e-02  1.12463368e-02  2.59630370e-03 ...  1.40836623e-02
   1.22406253e-02  7.92526949e-03]
 ...
 [-6.74545017e-03 -8.26472495e-03 -8.54968291e-04 ...  5.11250876e-03
   8.11213148e-03 -1.51852407e-02]
 [ 2.61424789e-02 -4.36562542e-03  7.43858690e-03 ... -1.24907905e-02
   2.24421992e-03  8.38081711e-03]
 [-4.16233657e-03  1.15111627e-02 -3.44686207e-03 ...  7.00084817e-03
   4.65215413e-03  1.71581106e-02]]


In [22]:
initial = 10000

portfolio = initial * np.cumprod(1 + returns, axis=0)

final_value = portfolio[-1]

print(final_values)


[21061.34959404 13305.47270826 13306.7422108  15525.97865247
 14515.95164771 10575.61964617 20865.85030129 12569.60140633
 12307.57004779 14848.24142764  8519.25866    15186.85352148
 13570.84290041 11505.8464679  11162.61730109 17185.07936697
  8765.60644733 12262.46945456 16316.5368999  16772.52859095
 20378.57078579 11777.7340925  10448.86569971 18008.86169279
 24372.81500197  9892.33225892 14398.92475301 14460.69829215
  7900.73443808  9642.97312364 16347.56361326 20279.13051857
 13657.96078899  7415.85107681  7631.42330136 22147.8915581
  7116.13634851 11426.81359913 13442.80715503 14903.92071166
 12061.88743873  7009.62295972 16237.39779498  8633.95574574
 19752.82182911  9957.48337613 20958.45976119 13985.54782274
  7669.55439036 13495.01820482 12095.69436934  6321.10652401
 14575.41244928  8935.28911742 16285.09538924  9991.57347936
 24211.75163061  8904.17188244 12189.75105077 12049.28661845
 15627.69091299 13504.70363502 14075.78522612  8485.48614117
 10378.22002688  8197.324

In [23]:
prob_loss = np.mean(final_values < initial)
print(prob_loss)

0.267


In [24]:
np.random.seed(42)

asset1 = np.random.normal(0.001, 0.02, 1000)

noise = np.random.normal(0, 0.01, 1000)

asset2 = 0.5 * asset1 + noise

In [25]:
cov_matrix = np.cov(asset1, asset2)
print(cov_matrix)

[[0.00038355 0.00018388]
 [0.00018388 0.00018749]]


In [26]:
import numpy as np

np.random.seed(42)
returns = np.random.normal(0.001, 0.02, 1000)

variance = np.var(returns)
volatility = np.std(returns)

print(variance)
print(volatility)

0.0003831619958926069
0.019574524154947086


In [27]:
asset1 = np.random.normal(0.001, 0.02, 1000)
asset2 = np.random.normal(0.001, 0.03, 1000)

w1 = 0.6
w2 = 0.4

cov_matrix = np.cov(asset1, asset2)

portfolio_variance = (
    w1**2 * cov_matrix[0,0] +
    w2**2 * cov_matrix[1,1] +
    2*w1*w2 * cov_matrix[0,1]
)

portfolio_volatility = np.sqrt(portfolio_variance)

print(portfolio_volatility)

0.01671460645513985


In [28]:
returns = np.random.normal(0.001, 0.02, 1000)

In [29]:
volatility = np.std(returns)
print(volatility)

0.020532376614310226


In [30]:
Var = np.percentile(returns, 5)
print(Var)

-0.034530598792274325


In [31]:
returns = np.random.normal(0.001, 0.02, 252)
print(returns)

[-0.01626987  0.00037593  0.00136034  0.01045261 -0.02633717  0.01285135
 -0.05308783 -0.01159769 -0.00876548  0.01366654  0.00145262 -0.02711126
 -0.01869986  0.0049736  -0.00058135 -0.01058248 -0.00861668  0.01492336
 -0.00935385 -0.00076182  0.04439873 -0.02747365 -0.03603685  0.01667179
 -0.01257286 -0.00536475 -0.01462313 -0.004196    0.03297076  0.01704257
  0.01824447 -0.02732454 -0.02202307 -0.05578157 -0.01518762  0.02013406
  0.01133893 -0.00343027  0.00055399 -0.01277771  0.00509518  0.01631757
 -0.03131774  0.00699295  0.0196487  -0.00730201  0.01501401  0.05729309
 -0.00108686  0.00886614 -0.01376114  0.00462502  0.01020543  0.00489685
 -0.01939391  0.00512724  0.03024392  0.00997272  0.02023974 -0.00374024
  0.015998    0.00658536 -0.01801821  0.00737042 -0.01883393 -0.01165761
  0.00478657  0.00694489 -0.02278465  0.02207972  0.01244013 -0.01309457
 -0.0297517  -0.00189809 -0.00791887  0.00326281 -0.00626233 -0.03914914
 -0.00676694 -0.00511238  0.01367322 -0.01296399  0

In [32]:
cum_return = np.cumprod(1 + returns) -1
print(cum_return)

[-0.01626987 -0.01590006 -0.01456135 -0.00426095 -0.03048589 -0.01802633
 -0.07015719 -0.08094122 -0.0889972  -0.07654695 -0.07520553 -0.10027787
 -0.11710255 -0.11271137 -0.1132272  -0.12261145 -0.13017163 -0.11719086
 -0.12544853 -0.12611478 -0.08731539 -0.11239017 -0.14437684 -0.13011206
 -0.14104904 -0.1456571  -0.15815027 -0.16168267 -0.13404271 -0.11928457
 -0.10321639 -0.12772059 -0.14693086 -0.1945164  -0.20674978 -0.19077842
 -0.18160272 -0.18441004 -0.18395821 -0.19438535 -0.1902806  -0.17706795
 -0.20284032 -0.19726582 -0.18149314 -0.18746988 -0.17527054 -0.12801925
 -0.12896696 -0.12124426 -0.13333694 -0.12932861 -0.12044303 -0.11613597
 -0.13327755 -0.12883366 -0.10248617 -0.09353553 -0.07518892 -0.07864793
 -0.06390814 -0.05774364 -0.07472141 -0.06790172 -0.0854568  -0.09611818
 -0.09179169 -0.08548429 -0.10632121 -0.08658904 -0.07522609 -0.08733561
 -0.11448892 -0.1161697  -0.12316864 -0.12030771 -0.12581663 -0.16004016
 -0.16572412 -0.16998925 -0.15864033 -0.16954771 -0

In [33]:
Var = np.percentile(returns, 5)
CVar = returns[returns <= Var].mean()
print(CVar)

-0.04632619178672884


In [34]:
asset1 = np.random.normal(0.001, 0.02, 1000)
noise = np.random.normal(0, 0.03, 1000)
asset2 = 0.5 * noise + asset1

cov_matrix = np.cov(asset1, asset2)
print(cov_matrix)

[[0.00038418 0.00037465]
 [0.00037465 0.00059487]]


In [35]:
asset1 = np.random.normal(0.001, 0.02, 1000)
asset2 = np.random.normal(0.001, 0.03, 1000)

w1 = 0.7
w2 = 0.3

cov_matrix = np.cov(asset1, asset2)

portfolio_variance = (
    w1**2 * cov_matrix[0, 0] +
    w2**2 * cov_matrix[1, 1] +
    2*w1*w2 * cov_matrix[0,1]
)
portfolio_volatility = np.sqrt(portfolio_variance)
print(portfolio_volatility)

0.01723407863432526


In [36]:
vol1 = np.std(asset1)
vol2 = np.std(asset2)
print(vol1,vol2,portfolio_volatility)

0.02084287897680404 0.03144612795003183 0.01723407863432526


In [37]:
np.random.seed(42)
simulations = 10000
days = 252
returns = np.random.normal(0.001, 0.02, (days, simulations))
final_values = np.prod(1 + returns, axis=0) -1

prob_large_loss = np.mean(final_values < -0.10)
print(prob_large_loss)


0.1699


In [38]:
import numpy as np

np.random.seed(42)
initial = 10000
days = 252
sims = 1000

# STOCK A: "The Steady Climber" (Strong Motor, Small Waves)
# Mean = 0.0015 (Higher), Volatility = 0.01 (Lower)
returns_A = np.random.normal(0.0015, 0.01, (days, sims))
final_A = initial * np.cumprod(1 + returns_A, axis=0)[-1]

# STOCK B: "The Wild Rider" (Weak Motor, Huge Waves)
# Mean = 0.0005 (Lower), Volatility = 0.04 (Higher)
returns_B = np.random.normal(0.0005, 0.04, (days, sims))
final_B = initial * np.cumprod(1 + returns_B, axis=0)[-1]

# Calculate Probability of Loss for both
prob_loss_A = np.mean(final_A < initial)
prob_loss_B = np.mean(final_B < initial)

print(f"Stock A (Steady) - Prob of Loss: {prob_loss_A:.2%}")
print(f"Stock B (Wild)   - Prob of Loss: {prob_loss_B:.2%}")


Stock A (Steady) - Prob of Loss: 1.40%
Stock B (Wild)   - Prob of Loss: 58.50%
